userのmodel,controller作成
DJ-phi/kakeibo pull request #1
Opened 2022-04-04 15:21 UTC by DJ-phi

実装した内容
user　modelを作成
user,index,new,show,editを作成
各アクションを追加
rspecを導入
現段階で可能なテストケースを記述

2022-04-05 00:51 UTC, ShunMinase requested changes
開発おつかれさまです！
いったん画面の見た目については何も触れずに、コードの書き方に重きを置いてレビューをしてみました！

基本が押さえられていていい感じです！！💪💪💪
知識量の面でまだまだぜんぜん伸びしろがあると思われるので、レビューを通していろいろとお伝えしてゆきますね🙆‍♂️🙆‍♂️

ポートフォリオ作成、すごく大変だとは思いますが、転職に向けて引き続き一緒に頑張りましょう！！！！！！！！

2022-04-05 00:51 UTC, ShunMinase commented on app/views/users/edit.html.erb
> +        <% render "error_message" %>
エラーメッセージ部分をパーシャル化したの、めちゃめちゃいい感じです！！！！

今の記述だと、モデルを増やすごとに`_error_message.erb`を増やさないといけないような作りになっていると思うので、
もう一歩上に行くために、以下の記事を参考にエラーメッセージ部分のパーシャルを作ってみてください🙆‍♂️🙆‍♂️
https://qiita.com/ryuuuuuuuuuu/items/1a1e53d062bff774d88a

2022-04-05 00:51 UTC, ShunMinase commented on app/views/users/new.html.erb
> +        <%= form_with model: @user do |f| %>
(ここに限りませんが)form_tagからform_withに書き換えたの、めちゃめちゃいい感じです！！！！！！！！

2022-04-05 00:51 UTC, ShunMinase commented on app/views/layouts/_header.html.erb
> +      <%= link_to "家計簿アプリとは", "/about" %>
ここは、aboutページができたら
`<%= link_to "家計簿アプリとは", about_path %>`
みたいな記述に書き換えましょう！

忘れないようにTODOコメントを使うとよいかもしれません🙆‍♂️🙆‍♂️

2022-04-05 00:51 UTC, ShunMinase commented on app/controllers/users_controller.rb
> +    @user = User.find(params[:id])
`@user = User.find(params[:id])`は、他のアクションでも登場するコードです。
このように繰り返し登場するコードはbefore_actionを活用して一か所にまとめましょう🙆‍♂️
[https://pikawaka.com/rails/before_action#同じ記述の処理をまとめたい場合](https://pikawaka.com/rails/before_action#%E5%90%8C%E3%81%98%E8%A8%98%E8%BF%B0%E3%81%AE%E5%87%A6%E7%90%86%E3%82%92%E3%81%BE%E3%81%A8%E3%82%81%E3%81%9F%E3%81%84%E5%A0%B4%E5%90%88)

2022-04-05 00:51 UTC, ShunMinase commented on app/controllers/users_controller.rb
> +      redirect_to user_path
ユーザー情報編集の際、この行でエラーになる気がします……！
動作確認をお願いします🙇‍♂️🙇‍♂️
(エラーにならなかったら無視してください！)

2022-04-05 00:51 UTC, ShunMinase commented on app/views/layouts/application.html.erb
> +    <%= render "layouts/header" %>
ヘッダーとフッターがパーシャル化されてるの、めちゃめちゃいい感じですね🙆‍♂️🙆‍♂️🙆‍♂️
こうしてあげると保守性がものすごく高くなるのでGOODです！

2022-04-05 00:51 UTC, ShunMinase commented on spec/factories/users.rb
> +    # traffic { 1 }
今後、交通費や食費というように、出費の種別も登録できるようにしたい場合は、カテゴリモデルが必要になってくる可能性があります……！
頭の片隅に入れておいていただけると幸いです🙆‍♂️🙆‍♂️

2022-04-05 00:51 UTC, ShunMinase commented on app/models/user.rb
> +class User < ApplicationRecord
面倒かもしれませんが、バリデーションを定義しましょう……！！！笑
バリデーションを追加したら、そのバリデーションがちゃんと動いているか検証するmodel specの実装もお願いします！

ここはセキュリティ的にめちゃめちゃ大事になってくるので、現場の人間が一番気にする部分です。
ここがしっかり実装できているとポイントが高くなるはずなのでぜひ……！

2022-04-05 00:51 UTC, ShunMinase commented on spec/requests/users_spec.rb
> +  # describe "GET /edit" do
create、edit、destroyのテストも定義しましょう🙆‍♂️🙆‍♂️
もし書き方がわからない場合はお知らせください！

2022-04-05 00:51 UTC, ShunMinase commented on app/views/users/edit.html.erb
> +        <%= form_with model: @user do |f| %>
editとnewのフォームはほぼほぼ同じ内容になることが多いので、このform_withもパーシャル化しましょう🙆‍♂️🙆‍♂️
以下手順です。

1. `view/users/_form.html.erb`を作成
2. `_form.html.erb`に、エラーメッセージ表示部分のrenderからform_withのendまで(6～19行目？)を全て移植
3. `_form.html.erb`の`<%= form_with model: @user do |f| %>`を`<%= form_with model: user do |f| %>`に変更
4. `<%= render 'form', user: @user %>`をedit.html.erbとnew.html.erbのフォームを表示したい部分に記載

文章だと伝わりづらいと思うので、疑問点がある場合や上手くいかない場合はお知らせください🙆‍♂️🙆‍♂️

2022-04-06 21:45 UTC, ShunMinase requested changes
修正おつかれさまです！めちゃめちゃいい感じでした！！！！
バリデーションと、app/controllers/users_controller.rbの14行目のみすごく惜しかったので、ぜひ修正をお願いします！！

rspecが実行できない件は別途ご連絡します🙆‍♂️🙆‍♂️

2022-04-06 21:45 UTC, ShunMinase commented on app/controllers/users_controller.rb
>      @user = User.new(params.require(:user).permit(:name, :email, :password))
こちらめちゃめちゃ惜しいです！！！！

知識の要素が大きいので答えをお伝えしてしまうと、ここは
`@user = User.(user_params)`
って感じで書けます！

次回以降はこんな感じで書いてゆきましょう💪

(って思ったけどupdateアクションの方はこの書き方になっているので単純に変更のし忘れ……？？？)

2022-04-06 21:45 UTC, ShunMinase commented on app/controllers/users_controller.rb
> +      redirect_to user_path(@user.id)
ここ、まさにそんな感じです！！！
showにアクセスしたい時は、`user_path(@user.id)`って感じでidを渡してあげる必要があります🙆‍♂️🙆‍♂️🙆‍♂️

めちゃめちゃいい感じです！！

2022-04-06 21:45 UTC, ShunMinase commented on app/views/users/_form.html.erb
> +<% end %>
パーシャル化、まさにこんな感じです！！！！！🙆‍♂️🙆‍♂️🙆‍♂️🙆‍♂️🙆‍♂️🙆‍♂️🙆‍♂️🙆‍♂️🙆‍♂️🙆‍♂️🙆‍♂️

2022-04-06 21:45 UTC, ShunMinase commented on app/views/layouts/_error_message.html.erb
> +<% end %>
ここ、実はだいぶ惜しい感じです！！！
たぶん後日、何が惜しいのかわかるはずなので、その時に直しましょう💪💪

2022-04-06 21:45 UTC, ShunMinase commented on app/controllers/users_controller.rb
> +  before_action :set_user, only: [:show, :edit, :update, :destroy]
before_action がしっかり活用できていますね！
`only: [:show, :edit, :update, :destroy]`というように、before_action を動かすアクションが指定されているのも理想的です🙆‍♂️🙆‍♂️

2022-04-06 21:45 UTC, ShunMinase commented on app/models/user.rb
> +class User < ApplicationRecord
バリデーションがしっかり実装できていますね🙆‍♂️🙆‍♂️
emailに`uniqueness:true`が付いているのも、目の付け所がいい感じです！！！！

欲を言うと、emailの形式チェックや、パスワードの文字数チェックがあるとなお良いです💪💪💪
今のままだと、メールアドレスとして成立していない文字列や1文字のパスワードでも登録ができてしまうので、セキュリティがだいぶガバガバです😂😂

ちなみにemailの形式チェックはこんな感じでいけるはずです！(いけなかったら教えてください)
https://k-koh.hatenablog.com/entry/2021/01/24/120210

2022-04-07 13:32 UTC, ShunMinase approved these changes
修正おつかれさまです！LGTMです！！！
(本当はrspecの実装も全て終わってからのほうがよいのですが、トラブルがあるようなので一旦マージしてしまいましょう！)

2022-04-07 13:37 UTC, DJ-phi commented
LGTMありがとう御座います🧟‍♂️

2022-04-07 13:37 UTC, merged