Login機能追加
DJ-phi/kakeibo pull request #2
Opened 2022-04-09 02:55 UTC by DJ-phi

実装内容
controllerにアクション, 処理を記述
before_action を使用
viewにif文追加

2022-04-26 07:39 UTC, ShunMinase requested changes
だんだんと実装のレベルが上がっていて素晴らしいです……！！！！！！
細かい部分で修正が必要な箇所はありますが、引き続き頑張ってゆきましょう！

2022-04-26 07:39 UTC, ShunMinase commented on spec/factories/users.rb
> +      name { Faker::Name.initials(number: 2) }
このままでは重複するnameが生成されてしまう恐れがあります。
念のため、
`name { Faker::Name.unique.initials(number: 2) }`
というようにuniqueを付けてあげると、値が重複しなくなります！(他の重複させたくない部分も同様)

2022-04-26 07:39 UTC, ShunMinase commented on spec/factories/users.rb
> +    trait :for_update2 do
こちら、無効な値でupdateできないことを確認するためのデータだと思うのですが、「for_update2」だとそれがわからないため、余裕があれば名前を変更されることをおすすめします🙆‍♂️🙆‍♂️

名付けは本当にめちゃめちゃ大事なので、メソッドや変数に対しては名前を見ただけで何をするメソッドなのか・何が入っている変数なのかがわかるような名前を付けてあげましょう💪💪

2022-04-26 07:39 UTC, ShunMinase commented on spec/support/login_request_module.rb
> +module SignInRequestModule
うわーー！！！rspecのログイン機構のモジュール化に成功されたんですね……！！！
素晴らしいです🎉🎉

2022-04-26 07:39 UTC, ShunMinase commented on app/views/users/login_form.html.erb
> +          <%= f.text_field :password %><br>
パスワードは、
`<%= f.password_field :password %>`
って感じでpassword_field を使うのがセキュリティ的にはおすすめです！

2022-04-26 07:39 UTC, ShunMinase commented on app/views/users/show.html.erb
>        <p><%= @user.password%></p>
セキュリティ的に、パスワードは画面に表示しないべきなので、ゆくゆくはこちらの行を削除されることをおすすめします🙆‍♂️🙆‍♂️

2022-04-26 09:24 UTC, DJ-phi commented
修正致しました！！

☆factorybot

uniqueを追加して重複回避

name { Faker::Name.unique.initials(number: 2) }
email { Faker::Internet.unique.free_email }

☆form_with文のpasswordの記述変更

text_field→password_fieldに変更
placeholder: "4文字以上,10文字以内"  #追加

showのパスワード, indexは完成後削除致します！

2022-04-26 09:33 UTC, DJ-phi commented
まだ実装されてないテストケースの移動

2022-04-27 17:59 UTC, ShunMinase commented
めちゃめちゃいい感じです！！
次の機能の実装も頑張ってゆきましょう！！！！💪💪

2022-04-27 18:00 UTC, ShunMinase approved these changes
めちゃめちゃいい感じです！！
次の機能の実装も頑張ってゆきましょう！！！！💪💪

2022-04-28 09:09 UTC, merged